Fixed link failure due to undefined symbols in libsss_cert.so
libtool: link: x86_64-alt-linux-gcc -Wall -Wshadow -Wstrict-prototypes -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Wundef -Werror-implicit-function-declaration -Winit-self -Wmissing-include-dirs -fno-strict-aliasing -std=gnu99 -pipe -frecord-gcc-switches -Wall -g -O2 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -o .libs/sss_ssh_authorizedkeys src/sss_client/sss_ssh_authorizedkeys-common.o src/sss_client/ssh/sss_ssh_authorizedkeys-sss_ssh_client.o src/sss_client/ssh/sss_ssh_authorizedkeys-sss_ssh_authorizedkeys.o  ./.libs/libsss_util.so ./.libs/libsss_crypt.so ./.libs/libsss_debug.so ./.libs/libsss_child.so -ltalloc -lpopt -ldl -Wl,-rpath -Wl,/usr/lib64/sssd
/usr/src/RPM/BUILD/sssd-1.16.2/.libs/libsss_cert.so: undefined reference to `exec_child_ex'
/usr/src/RPM/BUILD/sssd-1.16.2/.libs/libsss_cert.so: undefined reference to `child_io_destructor'
/usr/src/RPM/BUILD/sssd-1.16.2/.libs/libsss_cert.so: undefined reference to `child_handler_destroy'
/usr/src/RPM/BUILD/sssd-1.16.2/.libs/libsss_cert.so: undefined reference to `child_handler_setup'
collect2: error: ld returned 1 exit status